logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
    org.springframework.security.web.csrf: DEBUG
cloudinary:
  cloud_name: "bneikov"
  api_key: "133183588698468"
  api_secret: "qAeWm3WbSFi2eueRLC5GaabzjYs"
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/music_box?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    hidden-method:
      filter:
        enabled: true
  mail:
    host: "localhost"
    port: 1025
    username: "admin@musicbox.com"
    password: ""
app:
  default:
    password: topsecret
server:
  port: 8000
